### ISSUE TITLE
empty values in `config dataset=...` search

### ISSUE THREAD

**Issue by tiborsimko** [dmwm/dasgoclient#14]
@vkuznet I seem to have a problem with getting inputs/outpus for AOD datasets:

```console
$ /cvmfs/cms.cern.ch/common/dasgoclient \
    -query 'config dataset=/DoubleElectron/Run2012B-22Jan2013-v1/AOD' \
    -json | json_reformat 
[
  {
    "config": [
      {
        "dataset": "/DoubleElectron/Run2012B-22Jan2013-v1/AOD",
        "idict": {
          "byinputdataset": null,
          "byoutputdataset": null
        },
        "ids": null,
        "name": "ReqMgr2",
        "urls": {
          "input": null,
          "output": null
        }
      }
    ],
    "das": {
      "expire": 1512117104,
      "instance": "prod/global",
      "primary_key": "config.name",
      "record": 1,
      "services": [
        "reqmgr2:configs"
      ]
    },
    "qhash": "056f8d6b3784a2eb8f01a060d4475008"
  }
]
```

Can you please advise?  This is rather urgent since necessary for the preparations of the CMS 2012 open data release that is coming  in December... CC @katilp

**Comment by tiborsimko** [comment]
P.S. I'm using `cernapcms` account.

**Comment by katilp** [comment]
Just note that on lxplus with my grid  certificate I get that information, @vkuznet is there something we need to do to give the service account the rights to access?

**Comment by vkuznet** [comment]
Tibor,
few things you need to check:
- your account should be in CMS sitedb, you may go to `cmsweb.cern.ch/sitedb/` and
check it there
- you may have old das maps, just remove `~/.dasmaps` in your account and they'll
be re-populated
- you may use older version of dasgoclient, please post the version you run
`dasgoclient -version`
- you may inspect what dasgoclient is doing, just do
`dasgoclient -query="config dataset=/DoubleElectron/Run2012B-22Jan2013-v1/AOD" -verbose 2`
and you'll see which URL calls it makes, therefore you may use plain curl to
check if it works with credentials of your account
Best,
Valentin.

**Comment by tiborsimko** [comment]
Removed `~/.dasmaps` to no avail, the client I'm using is `/cvmfs/cms.cern.ch/common/dasgoclient` so it should be up to date (`Build: git=v01.00.12 go=go1.7.6 date=2017-12-03 01:27:22.714998055 +0100 CET`), I think the problem might be with the certificates of this "special" kind of account... I'll continue by email.

**Comment by tiborsimko** [comment]
All is well now after sitedb update; closing the issue.
