### ISSUE TITLE
Show only valid files if no 'status' option given in query

### ISSUE THREAD

**Issue by jhakala** [dmwm/dasgoclient#16]
To be consistent with the behavior of das_client, dasgoclient queries such as `file dataset=...` should use the `status=valid` option by default: das_client queries automatically require the files to be valid by default. Please see this hypernews: https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3479.html?inline=-1

**Comment by vkuznet** [comment]
John, the changes has been pushed to underlying library and scheduled in CMSSW, see
https://github.com/cms-sw/cmsdist/pull/3665

**Comment by vkuznet** [comment]
fixed and available in all CMSSW release now.
