### ISSUE TITLE
dasgoclient on FNAL HTCondor

### ISSUE THREAD

**Issue by basilschneider** [dmwm/dasgoclient#17]
I tried the new dasgoclient, and while it is working like a charm on the interactive machines, it does not on HTCondor.

dasgoclient fails with the error:
`panic: Unable to write DAS maps, error open //.dasmaps/das_maps_dbs_prod.js: no such file or directory`

Running it through `strace`, it seems the problem is a bunch of calls to `/afs`. The complete strace output can be seen here:
http://bschneid.web.cern.ch/bschneid/condor_1619295.0.stderr

**Comment by vkuznet** [comment]
Basil,
DAS tools need to load DAS maps which define mapping between DAS QL and CMS
data-service apis. These maps (by default) are stored (once) into $HOME/.dasmaps
area. It seems to me that your condor job does not define HOME environment,
if so you may define it and dasgoclient will create fetch das_maps_dbs_prod.js
into $HOME/.dasmaps

If such setup it is not desired I need to know a little bit more about
environment of HTCondor worker nodes that we can decide where and how to
place maps.

You may see logic here:
https://github.com/dmwm/das2go/blob/master/dasmaps/dasmaps.go#L398

Best,
Valentin.

**Comment by vkuznet** [comment]
Basil,
I adjusted code and added additional option to specify location of dasmaps.
You can find new static executable here:
/afs/cern.ch/user/v/valya/public/dasgoclient/dasgoclient_linux

Please try it out and let me know, e.g. you can do now
dasgoclient -dasmaps=/tmp -query=...
therefore you can adjust your condor job to use new option and may use any area
accessible to it (in example above it is /tmp). The dasmaps will be placed over
there, e.g. /tmp/.dasmaps/das_maps_dbs_prod.js

This change is scheduled in next CMSSW release build, so once it's accepted
the new dasgoclient will appear on cvmfs, see progress here:
https://github.com/cms-sw/cmsdist/pull/3743

Best,
Valentin.

**Comment by basilschneider** [comment]
I can confirm that setting the `HOME` environment in a condor job or using the new `dasgoclient` with the `dasmaps` flag fixes the issue.

**Comment by vkuznet** [comment]
good, I'll close the ticket.
