### ISSUE TITLE
Status of dataset different between web interface and command line client

### ISSUE THREAD

**Issue by mgratti** [dmwm/dasgoclient#23]
If I run the command

$ dasgoclient --query="dataset
dataset=/SMS-T1tttt_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16FSPremix-80X_mcRun2_asymptotic_v12-v1/AODSIM
status=VALID"

I get

/SMS-T1tttt_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16FSPremix-80X_mcRun2_asymptotic_v12-v1/AODSIM

However, If I search for this dataset from the das webtool, this dataset
appears as "DELETED".

**Comment by vkuznet** [comment]
THe fix has been applied to das2go codebase, see https://github.com/dmwm/das2go/commit/5e16d3c1359c771d164ec84ca5f3cebdd7eea5d2
Will propagate it to web UI and dasgoclient in next cmsweb upgrade.

**Comment by vkuznet** [comment]
in production
