### ISSUE TITLE
Create binaries for download

### ISSUE THREAD

**Issue by clelange** [dmwm/dasgoclient#26]
I think it would be nice if binary files for `linux-amd64` and `darwin-amd64` were created via the CI when you create a release. I'm using `dasgoclient` on my Mac, and this would make it much easier for me to keep the client up-to-date.

**Comment by vkuznet** [comment]
It is better later than never. Now, we have github actions and I automate creation of dagoclient binaries for every release. Please check release [page](https://github.com/dmwm/dasgoclient/releases). All binaries are there.
