### ISSUE TITLE
Pickign MC events turns up empty

### ISSUE THREAD

**Issue by sbein** [dmwm/dasgoclient#27]
While trying to retrieve the AOD file name based on the run#, lumi#, event# in an ntuple, I could do so with data but not with MC; for example:

edmPickEvents.py "/GJets_DR-0p4_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8_v2/RunIIFall17DRPremix-PU2017_94X_mc2017_realistic_v11-v1/AODSIM" 1:6525:43489036

with event numbers from my ntuple, just turned up:

edmCopyPickMerge outputFile=pickevents.root \
  eventsToProcess=1:43489036 \
  inputFiles=

Marguerite found the problem might be that dasgoclient doesn't like a run number of 1. She pointed us to this hypernews:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4764.html

Is there a known or potential fix, to get the AOD name starting from the event-level digits and dataset name?

**Comment by sixie** [comment]
Is anyone working on this problem? It is important for EXO analyses. Thanks! Si

**Comment by vkuznet** [comment]
not relevant for dasgoclient, closing
