### ISSUE TITLE
Lumi list for MC

### ISSUE THREAD

**Issue by kpedro88** [dmwm/dasgoclient#28]
This query returns nothing:
```
dasgoclient -query="lumi dataset=/SVJ_Zprime_Scan_TuneCP2_13TeV_pythia8/RunIIAutumn18MiniAOD-SVJ_PSweights_102X_upgrade2018_realistic_v15-v4/MINIAODSIM"
```

This query returns the desired result:
```
dasgoclient -query="run,lumi dataset=/SVJ_Zprime_Scan_TuneCP2_13TeV_pythia8/RunIIAutumn18MiniAOD-SVJ_PSweights_102X_upgrade2018_realistic_v15-v4/MINIAODSIM"
```
```
1 [40601,40607,40613,40614,42597,42604,42612,42618,40597,40598,40599,42600,42609,42616,40611,...]
```

This seems inconsistent.

**Comment by vkuznet** [comment]
Does it make sense to know lumi numbers w/o run number?

The DAS queries were setup based on use cases, no-one yet requested to look-up only lumi for a given dataset. If you provide clear use case I can add this query since it still will use fileRunLumi DBS API and DAS will just "hide" from user non-requested parts.

**Comment by kpedro88** [comment]
For MC, the run number is always 1, therefore kind of superfluous.

**Comment by vkuznet** [comment]
So it is specific case, not generic one. I don't know if it is worth it, but
I'll think about it.

**Comment by vkuznet** [comment]
I implement required logic in https://github.com/dmwm/das2go/commit/0d72b1bd338ab93b6617b58831d80e8b0094d9bc

To make it available now I need to push new DAS maps and deploy new das2go/dasgoclient to cmsweb/cmssw respectively. It may take a while.

**Comment by vkuznet** [comment]
DASMaps update is here: https://github.com/dmwm/DASMaps/pull/29

**Comment by vkuznet** [comment]
the changes are now scheduled into HG2005 production upgrade on cmsweb [1]. Once das server will be upgraded I'll prepare dasgoclient ones and propagate them to CMSSW.

[1] https://gitlab.cern.ch/cms-http-group/doc/issues/215

**Comment by vkuznet** [comment]
New dasgoclient which supports this query was merged into CMSSW, see https://github.com/cms-sw/cmsdist/pull/5736. The das web server will get this query support in the next cmsweb upgrade. I'm closing this ticket now.
