### ISSUE TITLE
dasgoclient fails to find /GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/GEN-SIM-RECO

### ISSUE THREAD

**Issue by belforte** [dmwm/dasgoclient#31]
just compare DAS Web output
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FGenericTTbar%2FHC-CMSSW_5_3_1_START53_V5-v1%2FGEN-SIM-RECO

with current dasgoclient. Note that query works with * as data tier, but when inserting the specific dataset name it fails. Dataset is valid (see the dasweb page).

I tried to refresh dasmaps in $HOME/.dasmaps by removing current file, but it did not make any difference
```
belforte@lxplus706/TC3> which dasgoclient 
/cvmfs/cms.cern.ch/common/dasgoclient
belforte@lxplus706/TC3> /cvmfs/cms.cern.ch/common/dasgoclient --version
Build: git=v02.04.37 go=go1.17.4 date=2022-01-09 11:14:07.810245734 +0100 CET m=+0.010101835
belforte@lxplus706/TC3> /cvmfs/cms.cern.ch/common/dasgoclient -query="dataset=/GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/*"
/GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/AODSIM
/GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/GEN-SIM-RAW
/GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/GEN-SIM-RECO
belforte@lxplus706/TC3> /cvmfs/cms.cern.ch/common/dasgoclient -query="dataset=/GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/GEN-SIM-RECO"
2022/01/09 11:14:22 ERROR, invalid URL /dbs/prod/global/DBSReader/datasetlist
/GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/GEN-SIM-RECO
ERROR: das exit with code: 2 , error: DBS unable to unmarshal the data into DAS record, api=datasetlist, data=, error=EOF
belforte@lxplus706/TC3> 
```

**Comment by belforte** [comment]
timestamp:
Sun Jan  9 11:17:42 CET 2022

the das web ui page which worked is dated
 DAS version: das2go git=c338f55 go=go1.17.5 date=2022-01-09 06:45:44.502467475 +0000 UTC m=+0.069199850

**Comment by vkuznet** [comment]
@belforte this issue was fixed already in https://github.com/cms-sw/cmsdist/pull/7522 but I don't know when new dasgoclient version will appear in `/cvmfs/cms.cern.ch/common/dasgoclient`. The new version which fixed  this issue is `Build: git=v02.04.38 ...`. @smuzaffar should tell us more.

**Comment by smuzaffar** [comment]
new dasgoclient will be deployed when we build a 12.3.X pre-release ( hopefully this week https://twiki.cern.ch/twiki/bin/view/CMS/CMSSW_12_3_0 )

**Comment by belforte** [comment]
thanks @vkuznet . Sorry for having reported again a known issue.
